"""
test_cases.py — /test-cases endpoints: read/write/upload Excel test case files.
Supports dynamic Excel file selection (not hardcoded to business_scenarios.xlsx).
Save is merge-based: only updates changed rows by Test ID, preserves all columns.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

import pandas as pd
from fastapi import APIRouter, HTTPException, UploadFile, File, Query
from pydantic import BaseModel

router = APIRouter()

_TEST_DATA_DIR = Path(__file__).parent.parent.parent / "test_data"
_DEFAULT_EXCEL = "business_scenarios.xlsx"


def _resolve_path(source: Optional[str]) -> Path:
    """Resolve Excel file path from optional source filename."""
    filename = source.strip() if source and source.strip() else _DEFAULT_EXCEL
    # Sanitise — only allow .xlsx files from test_data directory
    if not filename.endswith(".xlsx"):
        raise HTTPException(status_code=400, detail="Only .xlsx files are supported")
    path = _TEST_DATA_DIR / filename
    return path


@router.get("/test-cases/files")
def list_excel_files():
    """List all .xlsx files in the test_data directory, excluding temporary lock files."""
    _TEST_DATA_DIR.mkdir(parents=True, exist_ok=True)
    all_files = sorted(_TEST_DATA_DIR.glob("*.xlsx"), key=lambda p: p.stat().st_mtime, reverse=True)
    # Filter out temporary lock files generated by Excel (e.g. ~$business_scenarios.xlsx) and hidden files
    files = [f for f in all_files if not f.name.startswith("~") and not f.name.startswith(".")]
    return [
        {
            "filename": f.name,
            "sizeBytes": f.stat().st_size,
            "modifiedAt": f.stat().st_mtime,
        }
        for f in files
    ]


@router.get("/test-cases")
def get_test_cases(source: Optional[str] = Query(default=None)):
    """Read test cases from the specified Excel file (default: business_scenarios.xlsx)."""
    path = _resolve_path(source)
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"{path.name} not found in test_data/")
    df = pd.read_excel(path, dtype=str)
    records = df.where(df.notna(), None).to_dict("records")
    # Sanitise NaN/float artefacts
    clean = []
    for row in records:
        clean.append({
            str(k): (None if (v is None or str(v).strip().lower() == "nan") else str(v).strip())
            for k, v in row.items()
        })
    return clean


class TestCasePayload(BaseModel):
    rows: list[dict]
    source: Optional[str] = None  # target Excel filename


@router.post("/test-cases")
def save_test_cases(body: TestCasePayload):
    """
    Merge-save test case rows into the Excel file.
    - Reads the current Excel (if it exists)
    - For each incoming row, updates matched row by 'Test ID' OR appends new row
    - Preserves all existing columns; only updates columns present in the incoming data
    """
    path = _resolve_path(body.source)

    if path.exists():
        existing_df = pd.read_excel(path, dtype=str)
        existing_df = existing_df.where(existing_df.notna(), None)
    else:
        existing_df = pd.DataFrame()

    incoming_rows = body.rows

    if existing_df.empty:
        # Fresh file — write directly
        df_new = pd.DataFrame(incoming_rows)
    else:
        existing_df = existing_df.copy()
        existing_map: dict[str, int] = {}
        if "Test ID" in existing_df.columns:
            for idx, val in existing_df["Test ID"].items():
                if val:
                    existing_map[str(val).strip()] = int(idx)  # type: ignore[arg-type]

        rows_to_append = []
        for row in incoming_rows:
            tc_id = str(row.get("Test ID", "") or "").strip()
            if tc_id and tc_id in existing_map:
                # Update in-place — only touch columns present in incoming row
                df_idx = existing_map[tc_id]
                for col, val in row.items():
                    existing_df.at[df_idx, col] = val if val not in (None, "nan", "None", "") else None
            else:
                rows_to_append.append(row)

        if rows_to_append:
            append_df = pd.DataFrame(rows_to_append)
            existing_df = pd.concat([existing_df, append_df], ignore_index=True)

        df_new = existing_df

    _TEST_DATA_DIR.mkdir(parents=True, exist_ok=True)
    df_new.to_excel(path, index=False)
    return {"saved": len(df_new), "path": str(path)}


@router.post("/test-cases/upload")
async def upload_excel(file: UploadFile = File(...)):
    """Upload a new .xlsx file to test_data/."""
    if not (file.filename or "").endswith(".xlsx"):
        raise HTTPException(status_code=400, detail="Only .xlsx files are accepted")
    # Sanitise filename — strip path components
    safe_name = re.sub(r"[^\w\s\-.]", "_", Path(file.filename or "upload.xlsx").name)
    dest = _TEST_DATA_DIR / safe_name
    _TEST_DATA_DIR.mkdir(parents=True, exist_ok=True)
    contents = await file.read()
    dest.write_bytes(contents)
    return {"filename": safe_name, "sizeBytes": len(contents), "path": str(dest)}
