/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigsRouteImport } from './routes/configs'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as ExportRouteImport } from './routes/export'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as RunRouteImport } from './routes/run'
import { Route as TestCasesRouteImport } from './routes/test-cases'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsRoute = ConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesRoute = TestCasesRouteImport.update({
  id: '/test-cases',
  path: '/test-cases',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configs': typeof ConfigsRoute
  '/discovery': typeof DiscoveryRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/run': typeof RunRoute
  '/test-cases': typeof TestCasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configs': typeof ConfigsRoute
  '/discovery': typeof DiscoveryRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/run': typeof RunRoute
  '/test-cases': typeof TestCasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configs': typeof ConfigsRoute
  '/discovery': typeof DiscoveryRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/run': typeof RunRoute
  '/test-cases': typeof TestCasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configs'
    | '/discovery'
    | '/export'
    | '/history'
    | '/run'
    | '/test-cases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configs'
    | '/discovery'
    | '/export'
    | '/history'
    | '/run'
    | '/test-cases'
  id:
    | '__root__'
    | '/'
    | '/configs'
    | '/discovery'
    | '/export'
    | '/history'
    | '/run'
    | '/test-cases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigsRoute: typeof ConfigsRoute
  DiscoveryRoute: typeof DiscoveryRoute
  ExportRoute: typeof ExportRoute
  HistoryRoute: typeof HistoryRoute
  RunRoute: typeof RunRoute
  TestCasesRoute: typeof TestCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs': {
      id: '/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof ConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-cases': {
      id: '/test-cases'
      path: '/test-cases'
      fullPath: '/test-cases'
      preLoaderRoute: typeof TestCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigsRoute: ConfigsRoute,
  DiscoveryRoute: DiscoveryRoute,
  ExportRoute: ExportRoute,
  HistoryRoute: HistoryRoute,
  RunRoute: RunRoute,
  TestCasesRoute: TestCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
